### ISSUE TITLE
Scan code error

### ISSUE THREAD

**Issue by DragonBleak** [jm33-m0/wx2tg_bot#3]
When I scan the code, it tells me that the service is not available for this account.
![Image_20241001202223](https://github.com/user-attachments/assets/2dbf3f3d-b9b1-484b-bbbf-62ed5bd8c524)

**Comment by jm33-m0** [comment]
Yes Tencent has been deprecating WeChat Web and many users lost their access (if they were not actively using it).

**Comment by jm33-m0** [comment]
And there's no alternative to Web WeChat, unless you reverse engineer the desktop/mobile version.
